package haripackage;
import org.junit.Assert;
import org.junit.Test;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod_1() {
       // Library classUnderTest = new Library();
        System.out.println("***********************Hello Harinder_1*********************");
       // Assert.assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test 
    public void testSomeLibraryMethod_2() {
       // Library classUnderTest = new Library();
        System.out.println("***********************Hello Harinder_2*********************");
        //Assert.assertTrue("someLibraryMethod should return 'true'".equals("yetete"));
    }
}
